### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index 8599 out of bounds for length 8599

### ISSUE THREAD

**Issue by mibby** [boy0001/WorldEdit#10]
Paper dev 366 (Spigot 1.13.1)
FastAsyncWorldEdit compiled as of commit https://github.com/boy0001/WorldEdit/commit/9aaa77094e2bf1631c6606228ac7ee70600e1abb

Looked at a wall and typed /thru.

```
[00:15:18] [Server thread/INFO]: mibby issued server command: /thru
[00:15:19] [Craft Scheduler Thread - 21/INFO]: WorldEdit: mibby  (in "spawn"): thru
[00:15:19] [Craft Scheduler Thread - 21/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.ArrayIndexOutOfBoundsException: Index 8599 out of bounds for length 8599
	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.init(Spigot_v1_13_R2.java:97) ~[?:?]
	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.adapt(Spigot_v1_13_R2.java:518) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:132) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:440) ~[?:?]
	at com.boydti.fawe.wrappers.PlayerWrapper$10.get(PlayerWrapper.java:362) ~[?:?]
	at com.boydti.fawe.wrappers.PlayerWrapper$10.get(PlayerWrapper.java:350) ~[?:?]
	at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:400) ~[?:?]
	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18) ~[?:?]
	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:124) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-366]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-366]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by mibby** [comment]
Still occurring as of dev 99 and manual compile of PR branch as of commit https://github.com/boy0001/WorldEdit/pull/19/commits/9896a1339ef7a5aa3fa4565acdfdf8b517021175

```
[22:23:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 8599 out of bounds for length 8599
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.init(Spigot_v1_13_R2.java:106)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.adapt(Spigot_v1_13_R2.java:532)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:132)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:440)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.wrappers.WorldWrapper.getBlock(WorldWrapper.java:231)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.extent.InputExtent.getBlockType(InputExtent.java:55)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.util.TargetBlock.getSolidTargetBlock(TargetBlock.java:137)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.wrappers.PlayerWrapper$9.run(PlayerWrapper.java:338)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.wrappers.PlayerWrapper$9.run(PlayerWrapper.java:334)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.object.RunnableVal.runAndGet(RunnableVal.java:22)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.object.RunnableVal.get(RunnableVal.java:30)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:393)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:388)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:285)
[22:23:02] [Server thread/WARN]: 	at com.boydti.fawe.wrappers.PlayerWrapper.getSolidBlockTrace(PlayerWrapper.java:334)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:448)
[22:23:02] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
[22:23:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:23:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.WorldEdit.handleArmSwing(WorldEdit.java:519)
[22:23:02] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:138)
[22:23:02] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source)
[22:23:02] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[22:23:02] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[22:23:02] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:23:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[22:23:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:274)
[22:23:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:241)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1246)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[22:23:02] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[22:23:02] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[22:23:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[22:23:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
