### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16 - CraftChunkSnapshot.isSectionEmpty

### ISSUE THREAD

**Issue by mibby** [boy0001/WorldEdit#11]
Paper dev 368 (Spigot 1.13.1)
FastAsyncWorldEdit 1.13 dev 95

https://paste.ubuntu.com/p/5rXwzb8s3T/
```
[22:20:34] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
[22:20:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftChunkSnapshot.isSectionEmpty(CraftChunkSnapshot.java:117)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v0.BukkitQueue_All.getCombinedId4Data(BukkitQueue_All.java:227)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.v0.BukkitQueue_All.getCombinedId4Data(BukkitQueue_All.java:34)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:765)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.object.FaweQueue.getCombinedId4DataDebug(FaweQueue.java:452)
[22:20:34] [Server thread/WARN]: 	at com.sk89q.worldedit.EditSession.getBlockType(EditSession.java:986)
[22:20:34] [Server thread/WARN]: 	at com.sk89q.worldedit.EditSession.getBlockType(EditSession.java:979)
[22:20:34] [Server thread/WARN]: 	at com.sk89q.worldedit.function.mask.BlockTypeMask.test(BlockTypeMask.java:79)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.object.mask.MaskedTargetBlock.getMaskedTargetBlock(MaskedTargetBlock.java:24)
[22:20:34] [Server thread/WARN]: 	at com.sk89q.worldedit.command.tool.BrushTool$2.run(BrushTool.java:429)
[22:20:34] [Server thread/WARN]: 	at com.sk89q.worldedit.command.tool.BrushTool$2.run(BrushTool.java:426)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.object.RunnableVal.runAndGet(RunnableVal.java:22)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.object.RunnableVal.get(RunnableVal.java:30)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:400)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[22:20:34] [Server thread/WARN]: 	at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:124)
[22:20:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63)
[22:20:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[22:20:34] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008)
[22:20:34] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434)
[22:20:34] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[22:20:34] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[22:20:34] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by IronApollo** [comment]
Can you explain the action you were performing when this occurred and how to reproduce it? Thanks.

**Comment by mibby** [comment]
@IronApollo It usually happens the first time you try to /thru or /up. Typing it again, the command function works.

Maybe perhaps it happens the first time any FAWE command is used where it checks nearby blocks? As I had another ArrayIndexOutOfBoundsEeception occur right after a player typed ```/butcher 25```.

```
[02:18:09] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 8599 out of bounds for length 8599
[02:18:09] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.init(Spigot_v1_13_R2.java:97)
[02:18:09] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.adapt(Spigot_v1_13_R2.java:518)
[02:18:09] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:132)
[02:18:09] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:440)
[02:18:09] [Server thread/WARN]: 	at com.boydti.fawe.wrappers.PlayerWrapper$10.get(PlayerWrapper.java:362)
[02:18:09] [Server thread/WARN]: 	at com.boydti.fawe.wrappers.PlayerWrapper$10.get(PlayerWrapper.java:350)
[02:18:09] [Server thread/WARN]: 	at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:393)
[02:18:09] [Server thread/WARN]: 	at com.boydti.fawe.util.TaskManager.sync(TaskManager.java:289)
[02:18:09] [Server thread/WARN]: 	at com.boydti.fawe.wrappers.PlayerWrapper.passThroughForwardWall(PlayerWrapper.java:350)
[02:18:09] [Server thread/WARN]: 	at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:486)
[02:18:09] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor138.invoke(Unknown Source)
[02:18:09] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:18:09] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[02:18:09] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[02:18:09] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[02:18:09] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[02:18:09] [Server thread/WARN]: 	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[02:18:09] [Server thread/WARN]: 	at com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:531)
[02:18:09] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:157)
[02:18:09] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source)
[02:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[02:18:09] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[02:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[02:18:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:256)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:459)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1308)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[02:18:09] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[02:18:09] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[02:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[02:18:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
